require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::MattressesController do

  # This should return the minimal set of attributes required to create a valid
  # Mattress. As you add validations to Mattress, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    FactoryGirl.attributes_for(:mattress)
  end

  let(:user) { FactoryGirl.create(:user) }
  before :each do
    sign_in user
  end

  describe "GET index" do
    it "assigns all mattresses as @mattresses" do
      mattress = Mattress.create! valid_attributes
      mattress.product_series = FactoryGirl.create(:product_series)
      mattress.save
      get :index, {}
      assigns(:mattresses).should eq([mattress])
    end
  end

  describe "GET show" do
    it "assigns the requested mattress as @mattress" do
      mattress = Mattress.create! valid_attributes
      get :show, {:id => mattress.to_param}
      assigns(:mattress).should eq(mattress)
    end
  end

  describe "GET new" do
    it "assigns a new mattress as @mattress" do
      get :new, {}
      assigns(:mattress).should be_a_new(Mattress)
    end
  end

  describe "GET edit" do
    it "assigns the requested mattress as @mattress" do
      mattress = Mattress.create! valid_attributes
      get :edit, {:id => mattress.to_param}
      assigns(:mattress).should eq(mattress)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mattress" do
        expect {
          post :create, {:mattress => valid_attributes}
        }.to change(Mattress, :count).by(1)
      end

      it "assigns a newly created mattress as @mattress" do
        post :create, {:mattress => valid_attributes}
        assigns(:mattress).should be_a(Mattress)
        assigns(:mattress).should be_persisted
      end

      it "redirects to the created mattress" do
        post :create, {:mattress => valid_attributes}
        response.should redirect_to([:admin, Mattress.last])
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mattress as @mattress" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mattress.any_instance.stub(:save).and_return(false)
        post :create, {:mattress => {}}
        assigns(:mattress).should be_a_new(Mattress)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mattress.any_instance.stub(:save).and_return(false)
        post :create, {:mattress => {}}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mattress" do
        mattress = Mattress.create! valid_attributes
        # Assuming there are no other mattresses in the database, this
        # specifies that the Mattress created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mattress.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => mattress.to_param, :mattress => {'these' => 'params'}}
      end

      it "assigns the requested mattress as @mattress" do
        mattress = Mattress.create! valid_attributes
        put :update, {:id => mattress.to_param, :mattress => valid_attributes}
        assigns(:mattress).should eq(mattress)
      end

      it "redirects to the mattress" do
        mattress = Mattress.create! valid_attributes
        put :update, {:id => mattress.to_param, :mattress => valid_attributes}
        response.should redirect_to([:admin, mattress.reload])
      end
    end

    describe "with invalid params" do
      it "assigns the mattress as @mattress" do
        mattress = Mattress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mattress.any_instance.stub(:save).and_return(false)
        put :update, {:id => mattress.to_param, :mattress => {}}
        assigns(:mattress).should eq(mattress)
      end

      it "re-renders the 'edit' template" do
        mattress = Mattress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mattress.any_instance.stub(:save).and_return(false)
        put :update, {:id => mattress.to_param, :mattress => {}}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mattress" do
      mattress = Mattress.create! valid_attributes
      expect {
        delete :destroy, {:id => mattress.to_param}
      }.to change(Mattress, :count).by(-1)
    end

    it "redirects to the mattresses list" do
      mattress = Mattress.create! valid_attributes
      delete :destroy, {:id => mattress.to_param}
      response.should redirect_to(admin_mattresses_url)
    end
  end

end
