require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::ProductSeriesController do

  # This should return the minimal set of attributes required to create a valid
  # ProductSeries. As you add validations to ProductSeries, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    FactoryGirl.attributes_for(:product_series)
  end

  let(:user) { FactoryGirl.create(:user) }
  before :each do
    sign_in user
  end


  describe "GET index" do
    it "assigns all product_series as @product_series" do
      product_series = ProductSeries.create! valid_attributes
      get :index, {}
      assigns(:product_series).should include(product_series)
    end
  end

  describe "GET show" do
    it "assigns the requested product_series as @product_series" do
      product_series = ProductSeries.create! valid_attributes
      get :show, {:id => product_series.to_param}
      assigns(:product_series).should eq(product_series)
    end
  end

  describe "GET new" do
    it "assigns a new product_series as @product_series" do
      get :new, {}
      assigns(:product_series).should be_a_new(ProductSeries)
    end
  end

  describe "GET edit" do
    it "assigns the requested product_series as @product_series" do
      product_series = ProductSeries.create! valid_attributes
      get :edit, {:id => product_series.to_param}
      assigns(:product_series).should eq(product_series)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProductSeries" do
        expect {
          post :create, {:product_series => valid_attributes}
        }.to change(ProductSeries, :count).by(1)
      end

      it "assigns a newly created product_series as @product_series" do
        post :create, {:product_series => valid_attributes}
        assigns(:product_series).should be_a(ProductSeries)
        assigns(:product_series).should be_persisted
      end

      it "redirects to the created product_series" do
        post :create, {:product_series => valid_attributes}
        response.should redirect_to([:admin, ProductSeries.last])
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved product_series as @product_series" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProductSeries.any_instance.stub(:save).and_return(false)
        post :create, {:product_series => {}}
        assigns(:product_series).should be_a_new(ProductSeries)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProductSeries.any_instance.stub(:save).and_return(false)
        post :create, {:product_series => {}}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested product_series" do
        product_series = ProductSeries.create! valid_attributes
        # Assuming there are no other product_series in the database, this
        # specifies that the ProductSeries created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProductSeries.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => product_series.to_param, :product_series => {'these' => 'params'}}
      end

      it "assigns the requested product_series as @product_series" do
        product_series = ProductSeries.create! valid_attributes
        put :update, {:id => product_series.to_param, :product_series => valid_attributes}
        assigns(:product_series).should eq(product_series)
      end

      it "redirects to the product_series" do
        product_series = ProductSeries.create! valid_attributes
        put :update, {:id => product_series.to_param, :product_series => valid_attributes}
        response.should redirect_to([:admin, product_series.reload])
      end
    end

    describe "with invalid params" do
      it "assigns the product_series as @product_series" do
        product_series = ProductSeries.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProductSeries.any_instance.stub(:save).and_return(false)
        put :update, {:id => product_series.to_param, :product_series => {}}
        assigns(:product_series).should eq(product_series)
      end

      it "re-renders the 'edit' template" do
        product_series = ProductSeries.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProductSeries.any_instance.stub(:save).and_return(false)
        put :update, {:id => product_series.to_param, :product_series => {}}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested product_series" do
      product_series = ProductSeries.create! valid_attributes
      expect {
        delete :destroy, {:id => product_series.to_param}
      }.to change(ProductSeries, :count).by(-1)
    end

    it "redirects to the product_series list" do
      product_series = ProductSeries.create! valid_attributes
      delete :destroy, {:id => product_series.to_param}
      response.should redirect_to(admin_product_series_index_url)
    end
  end

end
